import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/shared/header/Header";
import Footer from "@/shared/footer/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "react-hot-toast";
import CustomProvider from "@/context/provider/CustomProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Marcella Distribution Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </CustomProvider>
      </body>
    </html>
  );
}
